language: java
jdk:
  - openjdk11

services:
  - docker

script:
  - ./gradlew check

after_success:
  - heroku login
  - ./gradlew bootBuildImage --builder heroku/spring-boot-buildpacks
  - heroku container:login
  - docker tag $IMAGE_NAME:latest registry.heroku.com/$REPO/web
  - docker push registry.heroku.com/$REPO/web
  - heroku config:set \
    SPRING_DATA_MONGODB_URI=$SPRING_DATA_MONGODB_URI \
    SPRING_DATA_MONGODB_DATABASE=$SPRING_DATA_MONGODB_DATABASE \
    AUTH0_AUDIENCE=$AUTH0_AUDIENCE \
    AUTH0_DOMAIN=$AUTH0_DOMAIN

deploy:
  provider: script
  script: heroku container:release web --app $REPO

after_deploy:
  - curl --location --request GET 'https://$REPO.herokuapp.com/actuator/health'