version: '3.1'

services:

  api:
    image: registry.heroku.com/vuttr-pvsoftware:0.0.1-SNAPSHOT
    ports:
      - 3000:3000
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017
      SPRING_DATA_MONGODB_DATABASE: vuttr
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example